### registrar usuario
POST  http://localhost:3001/usuarios/registro
content-type: application/json

{
  "nombre": "Jorge Luchetta",
  "email": "usuario@example.com",
  "password": "hola123",
  "direccion": "call 45 # 54 - 79",
  "ciudad": "Abadia",
  "pais": "Colombia",
  "codigo_postal": "080020",
  "rol": "true"
}

### actualizar usuario
POST  http://localhost:3001/usuarios/update/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoxLCJub21icmUiOiJKb3JnZSBMdWNoZXR0YSIsImVtYWlsIjoidXN1YXJpb0BleGFtcGxlLmNvbSJ9LCJpYXQiOjE3MDkwMDQ4MTMsImV4cCI6MTcwOTAwODQxM30.fxNMGoffmZ71mok3OwRZk0zeuQq082A8RuLhIWwYEdE

{
  "nombre": "Jorge Luchetta",
  "email": "jluchett@gmail.com",
  "direccion": "calle 46A # 54 - 46",
  "ciudad": "Abadia",
  "pais": "Colombia",
  "codigo_postal": "080020"
}

### iniciar sesion
POST  http://localhost:3001/usuarios/login
content-type: application/json

{
  "email": "jluchett@gmail.com",
  "password": "First18"
}

### Obtener perfil
GET http://localhost:3001/usuarios/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoxLCJub21icmUiOiJKb3JnZSBMdWNoZXR0YSIsImVtYWlsIjoiamx1Y2hldHRAZ21haWwuY29tIn0sImlhdCI6MTcxMDg2NzYzNiwiZXhwIjoxNzEwODcxMjM2fQ.SJVGS1ameNhAYmlt-gohjQy-A5jZQ6og0xrvvW6jnzI


### olvido contraseña
POST http://localhost:3001/usuarios/forgotpass
content-type: application/json

{
  "email": "jluchett@gmail.com"
}

### reset contraseña
PUT http://localhost:3001/usuarios/resetPass/25fd082f349d529191a8028cb6a522e1ef6881de
content-type: application/json

{
  "newPassword": "First18"
}