### Obtener lista pedidos
GET http://localhost:3001/pedidos/listar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoxLCJub21icmUiOiJKb3JnZSBMdWNoZXR0YSIsImVtYWlsIjoidXN1YXJpb0BleGFtcGxlLmNvbSJ9LCJpYXQiOjE3MDg4MDcyMTUsImV4cCI6MTcwODgxMDgxNX0.Hnt-DzFRJZQnIns9YwtFIHSQABh7rZJ7a8SCeTmEZQQ

### registrar pedido
POST http://localhost:3001/pedidos/crear
content-type: application/json

{
  "id_usuario": 1,
  "fecha": "2024-03-19T14:10:30Z",
  "estado": "Confirmado",
  "total": 38.58
}

### actualizar producto
PUT http://localhost:3001/productos/update/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoxLCJub21icmUiOiJKb3JnZSBMdWNoZXR0YSIsImVtYWlsIjoidXN1YXJpb0BleGFtcGxlLmNvbSJ9LCJpYXQiOjE3MDg4MDcyMTUsImV4cCI6MTcwODgxMDgxNX0.Hnt-DzFRJZQnIns9YwtFIHSQABh7rZJ7a8SCeTmEZQQ
content-type: application/json

{
  "nombre": "Mouse Genius",
  "descripcion": "Mouse inalambrico marca Genius",
  "precio": 7.87,
  "cantidad_disponible": 120,
  "imagen": "ruta/nueva/imagen.jpg"
}

### Obtener producto por id
GET http://localhost:3001/productos/get/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoxLCJub21icmUiOiJKb3JnZSBMdWNoZXR0YSIsImVtYWlsIjoidXN1YXJpb0BleGFtcGxlLmNvbSJ9LCJpYXQiOjE3MDg4MDcyMTUsImV4cCI6MTcwODgxMDgxNX0.Hnt-DzFRJZQnIns9YwtFIHSQABh7rZJ7a8SCeTmEZQQ
